// global / app base
export const SET_INSTALL_PWA_EVENT = 'SET_INSTALL_PWA_EVENT'

// ui-mode
export const RESET_UIMODE = 'RESET_UIMODE'
export const ENTER_UIMODE = 'ENTER_UIMODE'
export const LEAVE_UIMODE = 'LEAVE_UIMODE'
export const UIMODE_ANIMATION_END = 'UIMODE_ANIMATION_END'

// bgimg
export const INIT_BGIMG = 'INIT_BGIMG'
export const ADD_BGIMG = 'ADD_BGIMG'
export const REMOVE_BGIMG = 'REMOVE_BGIMG'
export const CHANGE_BGIMG = 'CHANGE_BGIMG'
export const LOADED_MAIN_BGIMG = 'LOADED_MAIN_BGIMG'

// location
export const LOCATION_UPDATE = 'LOCATION_UPDATE'
export const MAIN_KEY_UPDATE = 'MAIN_KEY_UPDATE'
export const APP_READY_UPDATE = 'APP_READY_UPDATE'

// page-title
export const UPDATE_PAGE_TITLE = 'UPDATE_PAGE_TITLE'

// side-menu
export const SWIPED_FROM_LEFT_EDGE = 'SWIPED_FROM_LEFT_EDGE'

// ship-list
export const SHIPLIST_INIT = 'SHIPLIST_INIT'
export const SHIPLIST_RESET = 'SHIPLIST_RESET'
export const SHIPLIST_CHANGE_COLLECTION = 'SHIPLIST_CHANGE_COLLECTION'
export const SHIPLIST_FILTER_ENTER = 'SHIPLIST_FILTER_ENTER'
export const SHIPLIST_FILTER_LEAVE = 'SHIPLIST_FILTER_LEAVE'
export const SHIPLIST_FILTER_INPUT = 'SHIPLIST_FILTER_INPUT'
export const SHIPLIST_COMPARE_ENTER = 'SHIPLIST_COMPARE_ENTER'
export const SHIPLIST_COMPARE_LEAVE = 'SHIPLIST_COMPARE_LEAVE'
export const SHIPLIST_COMPARE_RESET = 'SHIPLIST_COMPARE_RESET'
export const SHIPLIST_COMPARE_CHANGE_STATE = 'SHIPLIST_COMPARE_CHANGE_STATE'
export const SHIPLIST_COMPARE_UPDATE_LIST = 'SHIPLIST_COMPARE_LIST_UPDATE'
export const SHIPLIST_COMPARE_ADD = 'SHIPLIST_COMPARE_ADD'
export const SHIPLIST_COMPARE_REMOVE = 'SHIPLIST_COMPARE_REMOVE'
export const SHIPLIST_COMPARE_SORT = 'SHIPLIST_COMPARE_SORT'
export const SHIPLIST_COMPARE_SCROLL = 'SHIPLIST_COMPARE_SCROLL'

// equipment-list
export const EQUIPMENTLIST_INIT = 'EQUIPMENTLIST_INIT'
export const EQUIPMENTLIST_RESET = 'EQUIPMENTLIST_RESET'
export const EQUIPMENTLIST_CHANGE_COLLECTION = 'EQUIPMENTLIST_CHANGE_COLLECTION'
export const EQUIPMENTLIST_SCROLL = 'EQUIPMENTLIST_SCROLL'
export const EQUIPMENTLIST_HIGHLIGHT_COLUMN = 'EQUIPMENTLIST_HIGHLIGHT_COLUMN'
export const EQUIPMENTLIST_OBSERVER = 'EQUIPMENTLIST_OBSERVER'

// pages
export const PAGE_INIT = 'PAGE_INIT'
export const PAGE_RESET = 'PAGE_RESET'
export const PAGE_UPDATE = 'PAGE_UPDATE'

// fleets
export const FLEETS_INIT = 'FLEETS_INIT'
export const FLEETS_REFRESH = 'FLEETS_REFRESH'
export const FLEETS_NEW_BUILD = 'FLEETS_NEW_BUILD'
export const FLEETS_REMOVE_BUILD = 'FLEETS_REMOVE_BUILD'
export const FLEETS_UPDATE_BUILD = 'FLEETS_UPDATE_BUILD'
export const FLEETS_CURRENT_CHANGE_TAB = 'FLEETS_CURRENT_CHANGE_TAB'
