export const I18N_INIT = 'I18N_INIT'

// app-mode
export const RESET_APPMODE = 'RESET_APPMODE'
export const ENTER_APPMODE = 'ENTER_APPMODE'
export const LEAVE_APPMODE = 'LEAVE_APPMODE'
export const APPMODE_ANIMATION_END = 'APPMODE_ANIMATION_END'

// bgimg
export const INIT_BGIMG = 'INIT_BGIMG'
export const ADD_BGIMG = 'ADD_BGIMG'
export const REMOVE_BGIMG = 'REMOVE_BGIMG'
export const CHANGE_BGIMG = 'CHANGE_BGIMG'
export const LOADED_MAIN_BGIMG = 'LOADED_MAIN_BGIMG'

// location
export const LOCATION_UPDATE = 'LOCATION_UPDATE'

// page-title
export const UPDATE_PAGE_TITLE = 'UPDATE_PAGE_TITLE'

// side-menu
export const SWIPED_FROM_LEFT_EDGE = 'SWIPED_FROM_LEFT_EDGE'

// ship-list
export const SHIPLIST_INIT = 'SHIPLIST_INIT'
export const SHIPLIST_CHANGE_COLLECTION = 'SHIPLIST_CHANGE_COLLECTION'
export const SHIPLIST_FILTER_ENTER = 'SHIPLIST_FILTER_ENTER'
export const SHIPLIST_FILTER_LEAVE = 'SHIPLIST_FILTER_LEAVE'
export const SHIPLIST_FILTER_INPUT = 'SHIPLIST_FILTER_INPUT'
export const SHIPLIST_COMPARE_ENTER = 'SHIPLIST_COMPARE_ENTER'
export const SHIPLIST_COMPARE_LEAVE = 'SHIPLIST_COMPARE_LEAVE'
export const SHIPLIST_COMPARE_RESET = 'SHIPLIST_COMPARE_RESET'
export const SHIPLIST_COMPARE_CHANGE_STATE = 'SHIPLIST_COMPARE_CHANGE_STATE'
export const SHIPLIST_COMPARE_UPDATE_LIST = 'SHIPLIST_COMPARE_LIST_UPDATE'
export const SHIPLIST_COMPARE_ADD = 'SHIPLIST_COMPARE_ADD'
export const SHIPLIST_COMPARE_REMOVE = 'SHIPLIST_COMPARE_REMOVE'